#define INPUT_PIN_NUMBER 6

#define DEFAULT_INPUT_PIN1 14
#define DEFAULT_INPUT_PIN2 15
#define DEFAULT_INPUT_PIN3 18
#define DEFAULT_INPUT_PIN4 23
#define DEFAULT_INPUT_PIN5 24
#define DEFAULT_INPUT_PIN6 25

#define DEFAULT_INPUT_PINS_ARRAY DEFAULT_INPUT_PIN1, DEFAULT_INPUT_PIN2, DEFAULT_INPUT_PIN3, DEFAULT_INPUT_PIN4, DEFAULT_INPUT_PIN5, DEFAULT_INPUT_PIN6

