#define OUTPUT_PIN_NUMBER 8

#define DEFAULT_OUTPUT_PIN1 23
#define DEFAULT_OUTPUT_PIN2 24
#define DEFAULT_OUTPUT_PIN3 25
#define DEFAULT_OUTPUT_PIN4 8
#define DEFAULT_OUTPUT_PIN5 7
#define DEFAULT_OUTPUT_PIN6 12
#define DEFAULT_OUTPUT_PIN7 16
#define DEFAULT_OUTPUT_PIN8 20

#define DEFAULT_OUTPUT_PINS_ARRAY DEFAULT_OUTPUT_PIN1, DEFAULT_OUTPUT_PIN2, DEFAULT_OUTPUT_PIN3, DEFAULT_OUTPUT_PIN4, DEFAULT_OUTPUT_PIN5, DEFAULT_OUTPUT_PIN6, DEFAULT_OUTPUT_PIN7, DEFAULT_OUTPUT_PIN8


#define SIGNAL0 22
#define SIGNAL1 24
