#define OUTPUT_PIN_NUMBER 8

#define DEFAULT_OUTPUT_PIN1 1
#define DEFAULT_OUTPUT_PIN2 2
#define DEFAULT_OUTPUT_PIN3 3
#define DEFAULT_OUTPUT_PIN4 4
#define DEFAULT_OUTPUT_PIN5 5
#define DEFAULT_OUTPUT_PIN6 6
#define DEFAULT_OUTPUT_PIN7 7
#define DEFAULT_OUTPUT_PIN8 8

#define DEFAULT_OUTPUT_PINS_ARRAY DEFAULT_OUTPUT_PIN1, DEFAULT_OUTPUT_PIN2, DEFAULT_OUTPUT_PIN3, DEFAULT_OUTPUT_PIN4, DEFAULT_OUTPUT_PIN5, DEFAULT_OUTPUT_PIN6, DEFAULT_OUTPUT_PIN7, DEFAULT_OUTPUT_PIN8


#define SIGNAL0 22
#define SIGNAL1 24


